config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'fridges#index'
  
  resources :fridges do
    resources :foods
    resources :drinks
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drink.rb
class Drink < ApplicationRecord
  belongs_to :fridge
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :fridge
end

app/models/fridge.rb
class Fridge < ApplicationRecord
  has_many :foods, dependent: :destroy
  has_many :drinks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController

  def show
    @fridge = Fridge.find(params[:fridge_id])
    @drink = Drink.find(params[:id])
  end

  def new
    @fridge = Fridge.find(params[:fridge_id])
    @drink = Drink.new
  end

  def create
    @fridge = Fridge.find(params[:fridge_id])
    @fridge.drinks.create(drink_params)
    redirect_to "/fridges/#{@fridge.id}"
  end


  def edit
    @fridge = Fridge.find(params[:id])
    @drink = Drink.find(params[:id])
  end

  def update
    @fridge = Fridge.find(params[:fridge_id])
    @drink = Drink.find(params[:id])
    @drink.update(drink_params)
    redirect_to "/fridges/#{@fridge.id}/drinks/#{@drink.id}"
  end

  def destroy
    @fridge = Fridge.find(params[:fridge_id])
    @drink = Drink.find(params[:id])
    @drink.destroy
    redirect_to "/fridges/#{@fridge.id}"
  end

  private

  def drink_params
    params.require(:drink).permit(:name, :size, :alcoholic)
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @fridge = Fridge.find(params[:fridge_id])
    @foods = @fridge.foods
  end

  def new
    @fridge = Fridge.find(params[:fridge_id])
    @food = Food.new
  end

  def show
    @fridge = Fridge.find(params[:fridge_id])
    @food = Food.find(params[:id])
  end

  def create
    @fridge = Fridge.find(params[:fridge_id])
    @fridge.foods.create(food_params)
    redirect_to "/fridges/#{@fridge.id}"
  end

  def destroy
    @fridge = Fridge.find(params[:fridge_id])
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to "/fridges/#{@fridge.id}"
  end

  # edit and update don't work
  def edit
    @fridge = Fridge.find(params[:fridge_id])
  end

  def update
    @fridge = Fridge.find(params[:id])
    @fridge.update(fridge_params)
    redirect_to "/fridges/#{@fridge.id}"
  end

  private

  def food_params
    params.require(:food).permit(:name, :weight, :vegan, :date_added)
  end

end

app/controllers/fridges_controller.rb
class FridgesController < ApplicationController

  def index
    @fridges = Fridge.all
  end

  def new
    @fridge = Fridge.new
  end

  def show
    @fridge = Fridge.find(params[:id])
    @foods = @fridge.foods
    @drinks = @fridge.drinks
  end

  def create
    fridge = Fridge.create!(fridge_params)
    redirect_to fridge_path(fridge)
  end

  def destroy
    @fridge =  Fridge.find(params[:id])
    @fridge.destroy
    redirect_to "/fridges"
  end

  def edit
    @fridge = Fridge.find(params[:id])
  end

  def update
    @fridge = Fridge.find(params[:id])
    @fridge.update(fridge_params)
    redirect_to "/fridges/#{@fridge.id}"
  end

  private

  def fridge_params
    params.require(:fridge).permit(:location, :brand, :size)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/fridges_helper.rb
module FridgesHelper
end

app/views/drinks/edit.html.erb
<h1>Drink some <%=@drink.name%></h1>

<%= form_for @drink, url: fridge_drink_path do |f| %>
  <div class="form-group">
    How much is left: <%= f.text_field :size, class: "form-control", placeholder: "Size" %> oz.
  </div>
    <%= f.submit "Put Drink Back in Fridge", class: "btn btn-block btn-success" %>
  </div>
<% end %>

app/views/drinks/new.html.erb
<h1>Put a new drink in the fridge</h1>

<%= form_for @drink, url: fridge_drinks_path do |f| %>
  <div class="form-group">
    <%= f.text_field :name, class: "form-control", placeholder: "Name", autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.text_field :size, class: "form-control", placeholder: "Size" %>
  </div>
  <div class="form-group">
    <%= f.label :alcoholic%>
    <%= f.check_box :alcoholic, class: "form-control", placeholder: "Alcoholic" %>
  </div>
    <%= f.submit "Add Drink", class: "btn btn-block btn-success" %>
  </div>
<% end %>

app/views/drinks/show.html.erb
<h1><%=@drink.name%></h1>
<hr>
<div>
  Size: <%=@drink.size%> oz.
</div>
<div>
  Alcoholic: <%=@drink.alcoholic%>
</div>

<div>
 <%= link_to("Take a sip", "/fridges/#{@fridge.id}/drinks/#{@drink.id}/edit")%>
</div>

<div>
  <%= link_to("Trashcan", "/fridges/#{@fridge.id}/drinks/#{@drink.id}", method: :delete) %>
</div>

<hr>
<%= link_to "Back", "/fridges/#{@fridge.id}"%>

app/views/foods/index.html.erb
Food in <%= @fridge.location %>

<% @foods.map do |food| %>
  <%=food.name%>
<%end%>

app/views/foods/new.html.erb
<h1>Add a new food item</h1>
<hr>

<%= form_for @food, url: fridge_foods_path do |f| %>
  <div class="form-group">
    <%= f.text_field :name, class: "form-control", placeholder: "Name", autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.text_field :weight, class: "form-control", placeholder: "Weight" %>
  </div>
  <div class="form-group">
    <%= f.label :vegan %>
    <%= f.check_box :vegan, class: "form-control", placeholder: "Vegan" %>
  </div>
    <%= f.submit "Add Food", class: "btn btn-block btn-success" %>
  </div>
<% end %>

app/views/foods/show.html.erb
<h1><%=@food.name%></h1>
<hr>

<div>
Weight: <%= @food.weight%>
</div>
<div>
Vegan: <%= @food.vegan%>
</div>
<div>
Date Added: <%= @food.created_at%>
</div>

<div>
  <%= link_to("Eat food item", "/fridges/#{@fridge.id}/foods/#{@food.id}", method: :delete)%>
</div>

<hr>
<%= link_to "Back", "/fridges/#{@fridge.id}"%>

app/views/fridges/edit.html.erb
<h1>Edit Fridge Details</h1>
<hr>

<%= form_for @fridge do |f| %>
  <div class="form-group">
    <%= f.text_field :location, class: "form-control", placeholder: "Location", autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.text_field :brand, class: "form-control", placeholder: "Brand" %>
  </div>
  <div class="form-group">
    <%= f.text_field :size, class: "form-control", placeholder: "Size" %>
  </div>
    <%= f.submit "Update Fridge", class: "btn btn-block btn-success" %>
  </div>
<% end %>

app/views/fridges/index.html.erb
<h1>Fridges <a href= '/fridges/new'> (+) </a></h1>
<hr>
    <% @fridges.map do |fridge| %>
      <div> <strong><%= link_to("#{fridge.location}", fridge_path(fridge))%></strong> </div>
    <% end %>

app/views/fridges/new.html.erb
<h1>Add a new Fridge</h1>
<hr>

<%= form_for @fridge do |f| %>
  <div class="form-group">
    <%= f.text_field :location, class: "form-control", placeholder: "Location", autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.text_field :brand, class: "form-control", placeholder: "Brand" %>
  </div>
  <div class="form-group">
    <%= f.text_field :size, class: "form-control", placeholder: "Size" %>
  </div>
    <%= f.submit "Create Fridge", class: "btn btn-block btn-success" %>
  </div>
<% end %>

app/views/fridges/show.html.erb
<h1>Fridge in <%= @fridge.location %> </h1> <%= link_to("Delete Fridge", "/fridges/#{@fridge.id}", method: :delete) %>
<hr>
<h2>Fridge Details</h2>
<div>
Brand: <%= @fridge.brand %>
</div>

<div>
Size: <%= @fridge.size %> cubic ft
</div>

<div>
<%= link_to("Edit Details", "/fridges/#{@fridge.id}/edit") %>
</div>

<hr>

<h2>Food in Fridge <%= link_to("(+)", "/fridges/#{@fridge.id}/foods/new") %> </h2>
<%# <div>
<%= link_to("Look in the Fridge", "/fridges/#{@fridge.id}/foods")%>
<%# </div> %>

<% @foods.map do |food| %>
  <div><%= link_to("#{food.name}", "/fridges/#{@fridge.id}/foods/#{food.id}") %></div>
<%end%>

<hr>

<h2>Drinks in Fridge <%= link_to("(+)", "/fridges/#{@fridge.id}/drinks/new") %> </h2>
<% @drinks.map do |drink| %>
  <div> <%= link_to("#{drink.name}", "/fridges/#{@fridge.id}/drinks/#{drink.id}") %></div>
<% end%>

<hr>

<%=link_to "Back", "/fridges"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FridgeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>